matrix:
  include:
    - language: node_js
      before_install:
        - cd FrontEnd/
      install: 
        - npm install
      script:
        - npm test

    - language: python
      before_install:
        - cd BackEnd/
      install: 
        - pip install -r requirements.txt
      script:
        - python test.py
node_js:
  - '4'